# This is a basic workflow to help you get started with Actions

name: PR Check

# Controls when the workflow will run
on:
  pull_request:
    types: [synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 16.x
      
      - name: Clone modpacksource.code
        uses: actions/checkout@v3
        with: 
          repository: "hkmodmanager/ModpackSource.Code"
          path: code
      
      - name: NPM CI
        run: |
          cd code
          npm ci
          npm run build
      
      - name: Check
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_ID: ${{ github.event.pull_request.number }}
        run: |
          cd code
          npm run prCheck
          
